/*
 * This source file was generated by the Gradle 'init' task
 */
package vechinicle;

class vechinicle {
    private final int wheel;
    private final String brand;
    private int fuel;

    public void driveCar() {
        if (fuel==0){
            System.out.println("Empty tank");
        }else{
        fuel = fuel - 1;
    }
    }

    public int getFuel() {
        return fuel;
    }

    vechinicle(int wheel, String brand) {
        this.wheel = wheel;
        this.brand = brand;
        this.fuel = 10;
    }
}

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        vechinicle firstCar = new vechinicle(wheel:2,brand:"Vespa");
        firstCar.driveCar();
        System.out.println(firstCar.getFuel());
    }
}
