/*
 * This source file was generated by the Gradle 'init' task
 */
package backaccount;

import org.junit.jupiter.api.Test;

import backaccount.BankAccount.App;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    public float getMoney(String key) {
        
            System.out.println(saving.getMoney("10"));
}
