/*
 * This source file was generated by the Gradle 'init' task
 */
package quiz;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello Hell!";
    }

    public static void main(String[] args) {
        Scanner ScanIn = new Scanner(System.in);
        int A = ScanIn.nextInt();
        int B = ScanIn.nextInt();
        int C = ScanIn.nextInt();
        ScanIn.close();
        if (B > A) {
            for (int i = A; i <= B; i++) {
                System.out.println(i + " ");
            }
        } else {
            for (int i = B; i >= C; i--) {
                System.out.print(i + " ");
            }
        }
    }
}
