/*
 * This source file was generated by the Gradle 'init' task
 */
package t1;

public class App {
    public static void main(String[] args) {
        BankAccount[] a = { new Checking("444"), new Saving("5555") };
        for (int i = 0; i < a.length; i++) {
            a[i].deposit(500);
        }
    }
}
