/*
 * This source file was generated by the Gradle 'init' task
 */
package backaccount;

class BankAccount {
    private float money = 0;
    private final String key;
    public final String name;

    BankAccount(String name1, String key1) {
        this.name = name1;
        this.key = key1;
        this.money = 0;
    }

    public float getMoney(String key) {
        if (key == this.key) {
            return money;
        } else {
            System.out.println("Key Error");
            return -1;
        }
    }

    public void deposit(float amount, String key) {
        if (key == this.key) {
            if(amount>=0)
            money += amount;
        } else {
            System.out.println("Key Error");
        }
    }
public void withdraw(float amount,String key){
    if(key==this.key){
        if(money-amount>=0)
        money-=amount;
    }
}
    public class App {
        public String getGreeting() {
            return "Hello World!";
        }

        public static void main(String[] args) {
            BankAccount saving = new BankAccount("supakrit", "10");
            saving.deposit( 100, "10");
            System.out.println(saving.getMoney("10"));
        }
    }

}