/*
 * This source file was generated by the Gradle 'init' task
 */
package car;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Civi a = new Civi();
        a.addFuel(20);
        System.out.println(a.drivable());
        Car[] b = { new Civi(), new Camry() };
        for (int i = 0; i < b.length; i++) {
            System.out.println(b[i].brand);
        } 
    }
}























]


